openapi: 3.0.3
info:
  title: Feeds Management Service
  description: |
    The primary function of this service is to manage the RSS feeds the `fetcher` should use.
  version: 1.0.0
  contact:
    name: Gustavo Ferreira
    email: gustavojcoferreira@gmail.com
servers:
- url: http://localhost:{port}{basePath}
  description: Local development
  variables:
    port:
      default: '9000'
      enum:
      - '9000'
    basePath:
      default: '/api/v1'
      enum:
      - '/api/v1'
tags:
- name: maintenance
  description: Service maintenance operations
- name: feeds
  description: Feeds operations
paths:
  /healthcheck:
    get:
      tags:
      - maintenance
      summary: Check API service health
      description: Returns status of the API service.
      operationId: "healthcheck"
      responses:
        '200':
          description: Service is OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthcheckResponse"
        '500':
          description: Service is not healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
  /feeds:
    get:
      tags:
      - feeds
      summary: Get list of RSS feeds
      description: yolo
      operationId: "get_feeds"
      responses:
        '200':
          description: Service is OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthcheckResponse"
components:
  responses:
    '400':
      description: Invalid Parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiErrorResponse"
  schemas:
    ApiErrorResponse:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: Message explaining the error reason.
    HealthcheckResponse:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          enum:
          - OK
