openapi: 3.0.3
info:
  title: Feeds Management Service
  description: |
    The primary function of this service is to manage the RSS feeds the `fetcher` should use.
  version: 1.0.0
  contact:
    name: Gustavo Ferreira
    email: gustavojcoferreira@gmail.com
servers:
- url: http://localhost:{port}{basePath}
  description: Local development
  variables:
    port:
      default: '9000'
      enum:
      - '9000'
    basePath:
      default: '/api/v1'
      enum:
      - '/api/v1'
tags:
- name: maintenance
  description: Service maintenance operations
- name: feeds
  description: Feeds operations
paths:
  /healthcheck:
    get:
      tags:
      - maintenance
      summary: Check API service health
      description: Returns status of the API service.
      responses:
        '200':
          description: Service is OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckResponse'
        '500':
          description: Service is not healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /feeds:
    get:
      tags:
      - feeds
      summary: Get list of RSS feeds
      description: |
        This endpoint returns a list of RSS feeds.

        This is not a paginated list of RSS feeds.
      parameters:
      - in: query
        name: provider
        description: RSS feed provider
        schema:
          type: string
      - in: query
        name: category
        description: RSS feed category
        schema:
          type: string
      - in: query
        name: enabled
        description: RSS feed enabled
        schema:
          type: boolean
          default: true
      responses:
        '200':
          description: List of feeds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feeds'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      tags:
      - feeds
      summary: Add new RSS feed
      description: This endpoint adds a new RSS feed to the database.
      requestBody:
        description: feed to add to the database
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Feed'
      responses:
        '204':
          description: New RSS feed added successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: RSS feed URL already exists in the database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          $ref: '#/components/responses/InternalError'
  /feeds/{url}:
    put:
      tags:
      - feeds
      summary: Change RSS feed state
      description: This endpoint enables/disables a RSS feed.
      parameters:
      - in: path
        name: url
        required: true
        description: RSS feed URL
        schema:
          type: string
      requestBody:
        description: feed state
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/FeedState'
      responses:
        '204':
          description: Changed RSS feed state successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
    delete:
      tags:
      - feeds
      summary: Remove a RSS feed
      description: This endpoint removes an RSS feed from the database.
      parameters:
      - in: path
        name: url
        required: true
        description: RSS URL
        schema:
          type: string
      responses:
        '204':
          description: Removed RSS feed successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  responses:
    BadRequest:
      description: Invalid Parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
  schemas:
    ApiErrorResponse:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: Message explaining the error reason.
    HealthcheckResponse:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          enum:
          - OK
    Feeds:
      type: array
      items:
        $ref: '#/components/schemas/Feed'
    Feed:
      type: object
      required:
      - url
      - provider
      - category
      properties:
        url:
          type: string
        provider:
          type: string
        category:
          type: string
    FeedState:
      type: object
      required:
      - enabled
      properties:
        enabled:
          type: boolean