version: "3.9"
services:
  feeds_service:
    image: news-app/feeds-api-server:latest
    restart: always
    environment:
      - NEWS_APP_FEEDS_MGMT_DATABASE_HOST=database
      - NEWS_APP_FEEDS_MGMT_DATABASE_USERNAME=app_client
      - NEWS_APP_FEEDS_MGMT_DATABASE_PASSWORD=password
      - NEWS_APP_FEEDS_MGMT_DATABASE_DBNAME=news_feeds
      - ENV=develop
    ports:
      - "8080:9000"
    networks:
      - backend
    depends_on:
      - database
  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=news_feeds
      - MYSQL_USER=app_client
      - MYSQL_PASSWORD=password
    volumes:
      - ./feeds-mgmt-service/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
