version: "3.9"
services:
  feeds_api:
    image: news-app/feeds-api-server:latest
    restart: always
    # env_file: .env
    environment:
      - ENV=develop
    ports:
      - "8080:9000"
    networks:
      - backend

  feeds_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge
