version: "3.9"
services:
  feeds_service:
    image: news-app/feeds-api-server:latest
    restart: always
    environment:
      - NEWS_APP_FEEDS_MGMT_DATABASE_HOST=database
      - NEWS_APP_FEEDS_MGMT_DATABASE_USERNAME=app_client
      - NEWS_APP_FEEDS_MGMT_DATABASE_PASSWORD=password
      - NEWS_APP_FEEDS_MGMT_DATABASE_DBNAME=news_feeds
    ports:
      - 9000:8080
    networks:
      - backend
    depends_on:
      - database
  articles_service:
    image: news-app/articles-api-server:latest
    restart: always
    environment:
      - NEWS_APP_ARTICLES_MGMT_DATABASE_HOST=database
      - NEWS_APP_ARTICLES_MGMT_DATABASE_USERNAME=app_client
      - NEWS_APP_ARTICLES_MGMT_DATABASE_PASSWORD=password
      - NEWS_APP_ARTICLES_MGMT_DATABASE_DBNAME=news_articles
    ports:
      - 9001:8080
    networks:
      - backend
    depends_on:
      - database
  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./feeds-mgmt-service/dump.sql:/docker-entrypoint-initdb.d/a-dump.sql:ro
      - ./articles-mgmt-service/dump.sql:/docker-entrypoint-initdb.d/b-dump.sql:ro
      - ./database/dump.sql:/docker-entrypoint-initdb.d/c-dump.sql:ro
    networks:
      - backend
  fetcher_service:
    image: news-app/fetcher-server:latest
    restart: always
    environment:
      - NEWS_APP_FETCHER_FEEDSMGMTSERVICE_HOST=feeds_service
      - NEWS_APP_FETCHER_ARTICLESMGMTSERVICE_HOST=articles_service
      - NEWS_APP_FETCHER_OPTIONS_CYCLEPERIOD=60
    networks:
      - backend
    depends_on:
      - feeds_service
      - articles_service
networks:
  backend:
    driver: bridge
